# Generated by Django 5.0.2 on 2024-02-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('numbers_file', models.FileField(upload_to='uploads/csv/')),
                ('image', models.ImageField(upload_to='uploads/images/')),
                ('video', models.FileField(upload_to='uploads/videos/')),
                ('document', models.FileField(upload_to='uploads/documents/')),
                ('message', models.TextField()),
            ],
        ),
    ]
